disease: influenza
temporal_frequency: w
min_date: '2011-06-01'
max_date: '2020-06-01'
split_trainval: '2018-06-01'
split_valtest: '2019-06-01'
nuts_level: nuts3
split_berlin: false
horizon_size: 1
horizon_leadtime: 3
quantiles:
- 0.1
- 0.25
- 0.5
- 0.75
- 0.9
prediction_mode: regression
predict_difference: false
time_index_d: false
time_index_w: true
time_index_m: false
lag_column: incidence
lag_num: 1
sequence_length: 4
incidence_scalar: 10000
feature_popsize: true
feature_popdens: true
feature_gisd: true
feature_popage: true
normalization_method: zscore
log_transform:
- incidence
log_shift: 1.0
temporal_column: timestamp
target_column: incidence
id_column: nuts_node
pred_column: pred
verbose: 0
