from .shallowloader.shallowdataloadermanager import ShallowDataLoaderManager
from .graphloader.graphdataloadermanager import GraphDataLoaderManager
from .deeploader.deepdataloadermanager import DeepDataLoaderManager