name: experiment-self_non0-tgcn-boolean_neighbors_selfmn
id: '0001'
task: {}
child: deepmodel
model: tgcnmodel
model_hparams:
  hidden_size: 64
  num_layers: 2
  temporal_layers: 2
  dropout: 0.2
global_hparams:
  lr: 5.0e-05
  n_epochs: 10
  patience: 15
  min_delta: 0.001
  optimizer: adam
  optimizer_kwargs: null
  scheduler: plateau
  scheduler_kwargs: null
  loss: mse
